package com.SpringbootApp.peerproject.Service;

import java.util.Objects;

import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.SpringbootApp.peerproject.Entity.MessageEntity;
import com.SpringbootApp.peerproject.accessingdatamysql.MessageRepository;
import com.SpringbootApp.peerproject.dto.MessageDTO;

@Service
public class MsgServiceImpl implements MsgService {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	public MessageRepository msgRepository;

	@Override
	public int validateAndSave(MessageDTO dto) {
		int valid = 1;
		try {
			if (Objects.nonNull(dto)) {
				System.out.println("starting to validate fields");

				if (dto.getfName() != null && !dto.getfName().isEmpty()) {
					System.out.println(" fname is valid :" + dto.getfName());

					valid = 0;
				} else {
					System.out.println(" fname is invalid :");
					valid = 1;
				}

				if (valid == 0 && dto.gettName() != null && !dto.gettName().isEmpty()) {
					System.out.println("Tname is valid :" + dto.gettName());

					valid = 0;
				} else {
					System.out.println(" Tname is invalid :");
					valid = 1;
				}

				if (valid == 0 && dto.getMessage() != null && !dto.getMessage().isEmpty()) {
					System.out.println("Message is valid :" + dto.getMessage());
					valid = 0;
				} else {
					System.out.println("Message is invalid :");
					valid = 1;
				}

				System.out.println("Checking if all fields are entered");
				if (valid == 0) {
					System.out.println("informations are valid :" + valid);

					MessageEntity mEntity = new MessageEntity();
					System.out.println("copying data from dto to MessageEntity");
					BeanUtils.copyProperties(dto, mEntity);
					msgRepository.save(mEntity);
					System.out.println("saved data to the DB");
					System.out.println("SERVICE:------------ENDS : validateAndSave()-------------------------------");
					return 0;
				} else {
					System.out.println(" fields are missing, please enter the missing fields");
					return 1;
				}
			} else {
				System.out.println("dto is null");
				return 1;
			}
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
		System.out.println("LOGGER : SERVICE:------------ENDS : validateAndSave()-------------------------------");

		return 0;
	}

}
